import type { Market, Product } from "@bangla-blend/types";

export const activeCatalogRevision = "bd-price-list-2026-07-29";

export const markets: Market[] = [
  {
    code: "bd",
    label: "Bangladesh",
    shortLabel: "Bangladesh",
    currency: "BDT",
    enabled: true,
    domestic: true,
    dutiesMessage: "Domestic delivery options are shown at checkout.",
  },
  {
    code: "gb",
    label: "United Kingdom",
    shortLabel: "United Kingdom",
    currency: "GBP",
    enabled: true,
    domestic: false,
    dutiesMessage: "Import duties and taxes may be collected by local authorities.",
  },
  {
    code: "us",
    label: "United States",
    shortLabel: "United States",
    currency: "USD",
    enabled: true,
    domestic: false,
    dutiesMessage: "Import duties and taxes may apply to your delivery.",
  },
  {
    code: "ca",
    label: "Canada",
    shortLabel: "Canada",
    currency: "CAD",
    enabled: false,
    domestic: false,
    dutiesMessage: "This market will open after delivery and customs approval.",
  },
  {
    code: "eu",
    label: "European Union",
    shortLabel: "European Union",
    currency: "EUR",
    enabled: false,
    domestic: false,
    dutiesMessage: "This market will open after delivery and customs approval.",
  },
  {
    code: "au",
    label: "Australia & New Zealand",
    shortLabel: "AU & NZ",
    currency: "AUD",
    enabled: false,
    domestic: false,
    dutiesMessage: "This market will open after biosecurity and delivery approval.",
  },
  {
    code: "me",
    label: "Middle East",
    shortLabel: "Middle East",
    currency: "AED",
    enabled: false,
    domestic: false,
    dutiesMessage: "This market will open after delivery and customs approval.",
  },
];

const prices = (bdt: number, international: number) => ({
  bd: { amount: bdt, currencyCode: "BDT" as const },
  gb: { amount: Math.ceil(international * 0.78), currencyCode: "GBP" as const },
  us: { amount: international, currencyCode: "USD" as const },
});

export const sampleProducts: Product[] = [
  {
    id: "prod_sample_mezban",
    handle: "mezban-masala",
    title: "Mezban Masala",
    subtitle: "Authentic Chattogram spice blend for rich traditional dishes",
    description:
      "Bangla Blend Mezban Masala is a carefully crafted spice blend inspired by Chattogram’s famous Mezban cuisine. Ideal for beef mezban, beef curry, mutton and other rich traditional dishes, it brings bold, balanced flavour, deep aroma and rich natural colour to home cooking.",
    collection: "originals",
    region: "Chattogram",
    thumbnail: "/images/products/mezban-masala-product.webp",
    thumbnailAlt: "Bangla Blend Mezban Masala beside a traditional curry and whole spices",
    images: [],
    badges: ["Bestseller", "Signature blend"],
    variants: [
      {
        id: "variant_sample_mezban_75",
        title: "75 g",
        sku: "SAMPLE-MEZ-75",
        price: prices(200, 7).bd,
        inventoryQuantity: 30,
      },
      {
        id: "variant_sample_mezban_100",
        title: "100 g",
        sku: "SAMPLE-MEZ-100",
        price: prices(220, 7).bd,
        inventoryQuantity: 20,
      },
    ],
    eligibleMarkets: ["bd", "gb", "us"],
    flavor: { heat: 4, aroma: 5, sweetness: 1, smokiness: 3, earthiness: 4, intensity: 5 },
    bestSeller: true,
    createdAt: "2026-07-24T00:00:00.000Z",
    isPlaceholder: true,
    verified: false,
  },
  {
    id: "prod_sample_black_pepper",
    handle: "black-pepper",
    title: "Black Pepper",
    subtitle: "Premium whole black pepper with bold flavour and natural aroma",
    description:
      "Bangla Blend Black Pepper is made from carefully selected black peppercorns for bold flavour and a rich natural aroma. Use it in soups, curries, marinades, stir fries, grilled dishes and seasoning blends for a warm, mildly spicy finish.",
    collection: "reserve",
    region: "Origin pending verification",
    thumbnail: "/images/products/black-pepper-product.webp",
    thumbnailAlt: "Bangla Blend whole Black Pepper surrounded by warming spices",
    images: [],
    badges: ["Whole spice", "Reserve"],
    variants: [
      {
        id: "variant_sample_black_pepper_75",
        title: "75 g",
        sku: "SAMPLE-BLK-75",
        price: prices(250, 8).bd,
        inventoryQuantity: 20,
      },
    ],
    eligibleMarkets: ["bd", "gb", "us"],
    ingredients: "Whole black peppercorns.",
    flavor: { heat: 3, aroma: 4, sweetness: 0, smokiness: 1, earthiness: 4, intensity: 4 },
    createdAt: "2026-07-29T00:00:00.000Z",
    isPlaceholder: true,
    verified: false,
  },
  {
    id: "prod_sample_white_pepper",
    handle: "white-pepper-powder",
    title: "White Pepper Powder",
    subtitle: "Refined pepper warmth for soups, sauces and delicately coloured dishes",
    description:
      "Bangla Blend White Pepper Powder is finely ground for a smooth texture and refined flavour. Its mild heat and earthy aroma suit soups, sauces, marinades, stir fries, pasta, fried rice, seafood, chicken and other delicately coloured recipes.",
    collection: "reserve",
    region: "Origin pending verification",
    thumbnail: "/images/products/white-pepper-powder-product.webp",
    thumbnailAlt: "Bangla Blend White Pepper Powder with whole spices on a wooden table",
    images: [],
    badges: ["Fine ground", "Reserve"],
    variants: [
      {
        id: "variant_sample_white_pepper_75",
        title: "75 g",
        sku: "SAMPLE-WPP-75",
        price: prices(270, 9).bd,
        inventoryQuantity: 18,
      },
    ],
    eligibleMarkets: ["bd", "gb", "us"],
    ingredients: "Ground white pepper.",
    flavor: { heat: 2, aroma: 3, sweetness: 0, smokiness: 1, earthiness: 4, intensity: 3 },
    createdAt: "2026-07-28T00:00:00.000Z",
    isPlaceholder: true,
    verified: false,
  },
  {
    id: "prod_sample_fish",
    handle: "coxs-bazar-fish-masala",
    title: "Cox’s Bazar Fish Masala",
    subtitle: "A balanced coastal blend for fish, seafood and marinades",
    description:
      "Bangla Blend Cox’s Bazar Fish Masala is crafted to bring rich coastal flavour to grilled fish, barbecue, fried fish, curries and seafood marinades. Its balanced aromatic spices add savoury depth, inviting aroma and rich natural colour without overpowering the fish.",
    collection: "originals",
    region: "Cox’s Bazar",
    thumbnail: "/images/products/coxs-bazar-fish-masala-product.webp",
    thumbnailAlt: "Bangla Blend Cox’s Bazar Fish Masala beside grilled fish at sunset",
    images: [],
    badges: ["Bestseller", "Coastal blend"],
    variants: [
      {
        id: "variant_sample_fish_75",
        title: "75 g",
        sku: "SAMPLE-FSH-75",
        price: prices(200, 7).bd,
        inventoryQuantity: 24,
      },
      {
        id: "variant_sample_fish_100",
        title: "100 g",
        sku: "SAMPLE-FSH-100",
        price: prices(220, 7).bd,
        inventoryQuantity: 18,
      },
    ],
    eligibleMarkets: ["bd", "gb", "us"],
    flavor: { heat: 3, aroma: 4, sweetness: 1, smokiness: 1, earthiness: 2, intensity: 4 },
    bestSeller: true,
    createdAt: "2026-07-23T00:00:00.000Z",
    isPlaceholder: true,
    verified: false,
  },
  {
    id: "prod_sample_chili",
    handle: "hathazari-red-chili",
    title: "Hathazari Red Chilli Powder",
    subtitle: "Vibrant colour and balanced heat for everyday cooking",
    description:
      "Bangla Blend Hathazari Red Chilli Powder is made from carefully selected red chillies for vibrant colour, rich aroma and balanced heat. The stems and most seeds are removed before grinding for a smoother, cleaner powder suited to curries, stir fries, marinades, barbecue, snacks and traditional Bangladeshi recipes.",
    collection: "reserve",
    region: "Hathazari",
    thumbnail: "/images/products/hathazari-red-chilli-product.webp",
    thumbnailAlt: "Bangla Blend Hathazari Red Chilli Powder among dried chillies and spices",
    images: [],
    badges: ["Bestseller", "Reserve"],
    variants: [
      {
        id: "variant_sample_chili_100",
        title: "100 g",
        sku: "SAMPLE-HTZ-100",
        price: prices(200, 7).bd,
        inventoryQuantity: 12,
      },
      {
        id: "variant_sample_chili_125",
        title: "125 g",
        sku: "SAMPLE-HTZ-125",
        price: prices(220, 7).bd,
        inventoryQuantity: 10,
      },
    ],
    eligibleMarkets: ["bd", "gb"],
    ingredients: "Ground red chillies with stems and most seeds removed.",
    flavor: { heat: 4, aroma: 4, sweetness: 1, smokiness: 2, earthiness: 2, intensity: 5 },
    bestSeller: true,
    createdAt: "2026-07-22T00:00:00.000Z",
    isPlaceholder: true,
    verified: false,
  },
  {
    id: "prod_sample_shahi",
    handle: "shahi-garam-masala",
    title: "Shahi Garam Masala",
    subtitle: "A premium aromatic blend for biryani, korma and curries",
    description:
      "Bangla Blend Shahi Garam Masala combines carefully selected aromatic spices for rich flavour and a warm, royal aroma. Use it in biryani, pulao, korma, roast, rezala, curries and other Bangladeshi and South Asian dishes for balanced depth without overpowering the ingredients.",
    collection: "originals",
    region: "Bangladesh",
    thumbnail: "/images/products/shahi-garam-masala-product.webp",
    thumbnailAlt: "Bangla Blend Shahi Garam Masala surrounded by aromatic whole spices",
    images: [],
    badges: ["Bestseller", "Aromatic blend"],
    variants: [
      {
        id: "variant_sample_shahi_75",
        title: "75 g",
        sku: "SAMPLE-SHA-75",
        price: prices(250, 8).bd,
        inventoryQuantity: 26,
      },
      {
        id: "variant_sample_shahi_100",
        title: "100 g",
        sku: "SAMPLE-SHA-100",
        price: prices(300, 10).bd,
        inventoryQuantity: 20,
      },
    ],
    eligibleMarkets: ["bd", "gb", "us"],
    flavor: { heat: 2, aroma: 5, sweetness: 2, smokiness: 1, earthiness: 4, intensity: 4 },
    bestSeller: true,
    createdAt: "2026-07-27T00:00:00.000Z",
    isPlaceholder: true,
    verified: false,
  },
];

export const activeProductHandles = sampleProducts.map((product) => product.handle);

export function withMarketPrices(products: Product[], marketCode: string): Product[] {
  const market = markets.find((item) => item.code === marketCode) ?? markets[0]!;
  if (market.code === "bd") return products;
  return products.map((product) => ({
    ...product,
    variants: product.variants.map((variant) => ({
      ...variant,
      price: {
        amount: Math.ceil(
          market.currency === "GBP" ? variant.price.amount / 38 : variant.price.amount / 32,
        ),
        currencyCode: market.currency,
      },
    })),
  }));
}
